name: sync

on:
  schedule:
    # At minute 32 (picked randomly) past every 12th hour
    - cron: 32 */1 * * *
  workflow_dispatch:

jobs:
  calsync-bfg:
    runs-on: ubuntu-latest
    environment: bfg
    name: 🔁 Sync Events
    steps:
      - uses: StreetsAlliance/calsync@main
        with:
          discord-guild-id: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_GUILD_ID }}
          discord-bot-token: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_BOT_TOKEN }}
          google-calendar-id: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_CALENDAR_ID }}
          google-service-account-key-json: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_SERVICE_ACCOUNT_KEY_JSON }}
          event-prefix: ${{ vars.DISCORD_EVENTS_SYNC_EVENT_PREFIX }}
          commit: ${{ vars.DISCORD_EVENTS_SYNC_COMMIT }}
